name: Create Github Releases

on:
  push:
    tags:
      - '@dolphin/chrome-extension@*.*.*'

permissions:
  contents: write

jobs:
  chrome-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: pnpm

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build chrome extension
        working-directory: apps/chrome-extension
        run: npx turbo run build

      - name: Build firefox extension
        working-directory: apps/chrome-extension
        run: pnpm run build:firefox

      - name: Package chrome extension
        working-directory: apps/chrome-extension
        run: npx web-ext build --source-dir dist --filename {name}-{version}-chrome.zip

      - name: Package firefox extension
        working-directory: apps/chrome-extension
        run: npx web-ext build --source-dir dist-firefox --filename {name}-{version}-firefox.zip

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          body: Please refer to [CHANGELOG.md](https://github.com/lujunji4113/cloud-document-converter/blob/main/apps/chrome-extension/CHANGELOG.md) for details.
          files: apps/chrome-extension/web-ext-artifacts/*.zip
