name: Create Github Releases

on:
  push:
    tags:
      - '@dolphin/chrome-extension@*.*.*'

permissions:
  contents: write

jobs:
  chrome-extension:
    if: startsWith(github.ref_name, '@dolphin/chrome-extension')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Zip chrome extension
        working-directory: apps/chrome-extension
        run: (cd dist && zip -r ../chrome-extension.zip .)

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          body: Please refer to [CHANGELOG.md](https://github.com/lujunji4113/cloud-document-converter/blob/main/apps/chrome-extension/CHANGELOG.md) for details.
          files: apps/chrome-extension/chrome-extension.zip
